"""add_is_flagged

Revision ID: fb0cdebfcd18
Revises: 14d75b340795
Create Date: 2025-06-24 09:04:32.345893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0cdebfcd18'
down_revision: Union[str, Sequence[str], None] = '14d75b340795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'is_flagged')
    # ### end Alembic commands ###
