# .github/workflows/deploy.yml

name: Deploy to Production

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  # Job pertama: Menjalankan tes
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest

  # Job kedua: Membangun dan mempublikasikan image Docker
  build-and-push:
    # Jalankan job ini hanya jika job 'test' berhasil
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Ganti 'your-username' dengan username Docker Hub Anda
          tags: your-username/dear-diary-api:latest

  # Job ketiga: Melakukan deployment ke server
  deploy:
    # Jalankan job ini hanya jika job 'build-and-push' berhasil
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app/directory # Ganti dengan path di server Anda
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> .env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
            echo "ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}" >> .env
            echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env
            # Tambahkan secrets lain yang dibutuhkan
            
            docker-compose pull # Unduh image terbaru dari Docker Hub
            docker-compose up -d --remove-orphans # Mulai ulang layanan dengan image baru
            
            # Jalankan migrasi database setelah deployment
            docker-compose exec -T web alembic upgrade head